version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: magaludb
      TZ: America/Sao_Paulo
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
